version: '3.8'

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bylightdb
        restart: always
        volumes:
            - ./dbdump:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        depends_on:
            - db

    prestashop:
        depends_on:
            - db
        ports:
            - 80:80
            - 443:443
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            PS_INSTALL_AUTO: 0
            PS_ERASE_DB: 0
            DB_SERVER: db
            DB_USER: root
            DB_PASSWD: root
            DB_NAME: bylightdb
            PS_DEV_MODE: 0
            ALLOW_OVERRIDE: 1
            PS_DOMAIN: localhost:80
        restart: always
        volumes:
            - ./webprod:/var/www/html
            - ./ssl/:/etc/apache2/sites-available