version: '3.8'

services:
    WojowniczeZolwieNinja:
        ports:
            - 18032:80
            - 18033:443
        image: popularkiya/be_180320
        environment:
            PS_INSTALL_AUTO: 0
            PS_ERASE_DB: 0
            DB_SERVER: actina15.maas
            DB_USER: be_180320
            DB_PASSWD: root
            DB_NAME: be_180320
            PS_DEV_MODE: 0
            ALLOW_OVERRIDE: 1
            PS_DOMAIN: localhost:18032
            PS_DOMAIN_SSL: localhost:18033
        restart: always
        networks:
            - admin-mysql_default
networks:
    admin-mysql_default:
        external:
            name: admin-mysql_default